import AlanFears1 from '../assets/image/AlanFears1.png';
import AlanFears2 from '../assets/image/AlanFears2.png';
import AlanFears3 from '../assets/image/AlanFears3.png';
import AlanFears4 from '../assets/image/AlanFears4.png';
import AlanFears5 from '../assets/image/AlanFears5.png';
import CarstenBeck1 from '../assets/image/CarstenBeck1.png';
import CarstenBeck2 from '../assets/image/CarstenBeck2.png';
import AndersSCRMNMeisner1 from '../assets/image/AndersSCRMNMeisner1.png';
import AndersSCRMNMeisner2 from '../assets/image/AndersSCRMNMeisner2.png';
import EddieMartinez1 from '../assets/image/EddieMartinez1.png';
import EddieMartinez2 from '../assets/image/EddieMartinez2.png';
import DennisOsadebe1 from '../assets/image/DennisOsadebe1.png';
import DennisOsadebe2 from '../assets/image/DennisOsadebe2.png';
import CharmingBaker1 from '../assets/image/CharmingBaker1.png';
import CharmingBaker2 from '../assets/image/CharmingBaker2.png';
import AyakoOkuda1 from '../assets/image/AyakoOkuda1.png';
import AyakoOkuda2 from '../assets/image/AyakoOkuda2.png';
import FayeWeiWei1 from '../assets/image/FayeWeiWei1.png';
import FayeWeiWei2 from '../assets/image/FayeWeiWei2.png';
import AndrewScott1 from '../assets/image/AndrewScott1.png';
import AndrewScott2 from '../assets/image/AndrewScott2.png';
import AndrewScott3 from '../assets/image/AndrewScott3.png';
import RonHicks1 from '../assets/image/RonHicks1.png';
import RonHicks2 from '../assets/image/RonHicks2.png';
import CaroleEisner1 from '../assets/image/CaroleEisner1.png';
import CaroleEisner2 from '../assets/image/CaroleEisner2.png';
import SusannahPhillips1 from '../assets/image/SusannahPhillips1.png';
import SusannahPhillips2 from '../assets/image/SusannahPhillips2.png';
import SusannahPhillips3 from '../assets/image/SusannahPhillips3.png';
import SamFrancis1 from '../assets/image/SamFrancis1.png';
import SamFrancis2 from '../assets/image/SamFrancis2.png';
import SamFrancis3 from '../assets/image/SamFrancis3.png';
import HyewonKim1 from '../assets/image/HyewonKim1.png';
import HyewonKim2 from '../assets/image/HyewonKim2.png';
import LeeSejun1 from '../assets/image/LeeSejun1.png';
import LeeSejun2 from '../assets/image/LeeSejun2.png';
import LeeSejun3 from '../assets/image/LeeSejun3.png';
import ChangSungeun1 from '../assets/image/ChangSungeun1.png';
import ChangSungeun2 from '../assets/image/ChangSungeun2.png';
import ChangSungeun3 from '../assets/image/ChangSungeun3.png';
import JihyunIm1 from '../assets/image/JihyunIm1.png';
import JihyunIm2 from '../assets/image/JihyunIm2.png';
import JihyunIm3 from '../assets/image/JihyunIm3.png';
import InKyungKwon1 from '../assets/image/InKyungKwon1.png';
import InKyungKwon2 from '../assets/image/InKyungKwon2.png';
import InKyungKwon3 from '../assets/image/InKyungKwon3.png';
import LeeKiyoung1 from '../assets/image/LeeKiyoung1.png';
import JungJungyeob1 from '../assets/image/JungJungyeob1.png';
import JungJungyeob2 from '../assets/image/JungJungyeob2.png';
import JungJungyeob3 from '../assets/image/JungJungyeob3.png';
import ItsukiKaito1 from '../assets/image/ItsukiKaito1.png';
import ItsukiKaito2 from '../assets/image/ItsukiKaito2.png';
import ItsukiKaito3 from '../assets/image/ItsukiKaito3.png';
import ChangukBak1 from '../assets/image/ChangukBak1.png';
import ChangukBak2 from '../assets/image/ChangukBak2.png';
import ChangukBak3 from '../assets/image/ChangukBak3.png';
import JungChoonpyo1 from '../assets/image/JungChoonpyo1.png';
import JungChoonpyo2 from '../assets/image/JungChoonpyo2.png';
import JungChoonpyo3 from '../assets/image/JungChoonpyo3.png';
import ZikSeongJeong1 from '../assets/image/ZikSeongJeong1.png';
import ZikSeongJeong2 from '../assets/image/JEONGZIKSEONG2.png';
import ZikSeongJeong3 from '../assets/image/JEONGZIKSEONG3.png';
import ZikSeongJeong4 from '../assets/image/JEONGZIKSEONG4.png';
import ZikSeongJeong5 from '../assets/image/JEONGZIKSEONG5.png';
import slide1 from '../assets/image/slide1.jpg';
import slide2 from '../assets/image/slide2.jpg';
import JohannesDaniel1 from '../assets/image/JohannesDaniel1.png';
import JohannesDaniel2 from '../assets/image/JohannesDaniel2.png';
import JohannesDaniel3 from '../assets/image/JohannesDaniel3.png';
import JohannesDaniel4 from '../assets/image/JohannesDaniel4.png';
import JohannesDaniel5 from '../assets/image/JohannesDaniel5.png';
import JungHyukPARK1 from '../assets/image/JungHyukPARK1.png';
import JungHyukPARK2 from '../assets/image/JungHyukPARK2.png';
import KIMIlChi1 from '../assets/image/KIMIlChi1.png';
import KIMIlChi2 from '../assets/image/KIMIlChi2.png';
import HwiyeonKim1 from '../assets/image/HwiyeonKim1.png'
import HwiyeonKim2 from '../assets/image/HwiyeonKim2.png'
import HwiyeonKim3 from '../assets/image/HwiyeonKim3.png'

const slide = [
    {
        name: 'Kiaf SEOUL 2024',
        img: slide1.src,
        date: '2024.09.12-09.30',
        location: 'Coex 1F, Hall A & B; 2F The Platz, Seoul',
        link: 'https://kiaf.org/visit-ticket',
    },
    {
        name: 'Frieze Seoul 2024',
        img: slide2.src,
        date: '2024.09.17-10.05',
        location: ' COEX, 513 Seoul',
    },
];

const gallery1 = { name: 'SPACE Willing N Dealing' };
const gallery2 = { name: 'GalleryMEME' };
const gallery3 = {
    name: 'art B project',
    info: '다양한 아트 매개 시스템을 운영하는 아트 회사입니다. ARTS와 함께 해외에서 거의 선보이지 않았던 한국의 신진, 중견, 중견 아티스트를 소개합니다. 새로운 한국 아트를 찾고 있다면 art B project가 최고의 파트너가 될 것입니다! 한국에 거주하는 아티스트를 지원하기 위해 아티스트 에이전시를 운영합니다. 또한 한국 아티스트와 함께 개인 아트 컬렉터를 위한 아트 컨설팅, 기업과의 협업, 아트 협업 등 귀중한 프로젝트를 진행합니다.',
};
const gallery4 = {
    name: 'unbound',
    info: 'unbound는 다양한 예술 형식을 탐구하는 데 전념하는 창의적인 아트 랩입니다. 저희 공간은 창의성이 경계를 모르는 역동적인 허브로, 시각 예술, 디지털 예술, 음악 공연, 연극 및 멀티미디어 프로젝트에서 광범위한 예술적 표현을 선보입니다. unbound는 기존의 경계에 도전하고 아티스트와 관객 간의 견고한 관계를 구축하기 위해 프로젝트를 선택하고 큐레이팅합니다',
};
const gallery5 = {
    name: 'Rutger Brandt Gallery',
    info: 'Rutger Brandt Gallery는 사회적으로 참여하고 내러티브한 현대 미술을 선보이는 데 전념하며, 다세대 프로그램에서 떠오르는 젊은 아티스트와 이미 자리를 잡은 국제 아티스트를 모두 선보입니다. 저희의 사명은 현 시대 정신을 반영하는 현대 정치와 현대적 주제를 다루는 생각을 자극하는 작품을 만드는 아티스트를 홍보하는 것입니다. 저희의 다양한 아티스트는 현대 사회의 소외, 고립, 부조리와 같은 인간 경험과 관계의 다양한 측면을 탐구합니다. 다양한 매체를 사용하여 저희 아티스트는 전통적인 표현 형식에 도전하고 일상 생활의 예상치 못한 측면을 밝혀 자기 반성과 세계적 인식을 장려합니다',
};
const gallery6 = {
    name: 'Artbn',
    info: 'ARTBN은 2007년에 설립된 새로운 예술 프로젝트 및 매니지먼트 그룹입니다. 우리는 all for arts를 기반으로 21세기 글로벌 시대에 표현되는 다양성과 차별화를 추구하며 문화적, 예술적 감성을 기반으로 한 예술 프로젝트를 진행하고 있습니다. ARTBN은 창의성, 독창성, 시작이라는 의미를 담고 있습니다. 2015년 우리는 서울 삼청동의 아트 허브 지역 중심에 새로운 공간을 열었습니다. 우리는 다양한 분야의 예술가들의 광범위한 예술 프로젝트와 전시를 선보입니다. 우리의 사명은 민간 및 공공 부문 모두를 위해 현대 미술을 교차문화적으로 홍보하는 것입니다. 또한 우리는 다른 독립 큐레이터, 갤러리, 박물관, 사립 기관 및 기업 그룹과 협력할 수 있는 환경을 적극적으로 장려합니다',
};
const gallery7 = {
    name:'AVO',
    info:'2024년 서울에서 창립한 AUGUST VIBES ONLY는 누구나 쉽게 전시를 즐길 수 있는 아트 스페이스를 운영하고 있습니다. 갤러리 내 현대 미술 전시뿐만 아니라 다양한 기업과의 협업, 신뢰할 수 있는 아트 자문, 개인 소장품 판매를 통해 대중에게 다가가 사람들이 예술에 참여할 수 있도록 돕고 작가들에게 풍부한 기회를 제공하고자 노력합니다. 잠재적인 작가를 육성하는 매니지먼트 프로젝트를 구축하고 컬렉터의 요구에 부합하는 온라인 마켓플레이스를 구축하여 한국 미술 시장의 확대와 글로벌 미술계 진출에 기여하는 아트 컴퍼니로 나아갈 계획입니다'

}
const AlanFears = {
    name: 'Alan Fears',
    info: '앨런 피어스는 영국의 신진 예술가입니다. "순진한 예술가, 그래픽 아티스트, 팝 아티스트... 저는 이 둘의 일부입니다." 피어스가 말했습니다. "제 스타일은 단순하고 직접적입니다. 제 예술의 대부분 주제는 저 자신과 다른 모든 사람에게 인간이 얼마나 위대하고 어리석을 수 있는지, 그리고 따라서 삶이 얼마나 위대하고 어리석을 수 있는지 상기시키는 것입니다." 피어스는 2018년과 2020년에 모두 최고의 현대 회화에 수여되는 존 무어스 회화상 후보에 올랐습니다. 그의 작품은 문학 및 예술 잡지인 The Paris Review 의 2019년 여름호 표지에 실렸습니다 .',
};
const CarstenBeck = {
    name: 'Carsten Beck',
    info: '덴마크 예술가 카르스텐 베크(1986년 출생)는 덴마크 코펜하겐에서 거주하며 작업합니다. 그의 그림은 캔버스에 오일로 번역된 스칸디나비아 미니멀리즘 표현으로 간주될 수 있습니다. 이 예술 작품은 모양과 인물의 기하학적 관점과 세부 사항에 대한 수학적 관심과 고품질 소재의 혼합입니다. 베크의 판화와 사진 분야 배경은 그에게 강력하고 모순되는 색상 조합으로 새로운 기하학적 형태를 창조하면서 예술에서 다른 관점을 볼 수 있는 옵션을 제공합니다. Beck의 예술 작품을 만드는 가장 큰 영감은 새로운 관점과 각도를 포착하기 위해 긴 산책을 하는 데서 나옵니다. 그는 이 영감을 새로운 스케치와 아이디어로 해석합니다. Beck은 자신의 작업을 중세 예술과 연관시키는 동시에 영감을 얻으려고 합니다. 게다가 그의 가장 좋아하는 건축가 중 한 명은 Alvar Aalto입니다. 그의 예술은 반드시 그림 이상의 것을 표현하거나 반영할 필요는 없습니다. 때로는 사물이 의미가 있거나 구체적인 것을 표현할 필요가 없기 때문입니다. 실제로는 구성과 흑백의 균형, 색상의 층에서 인물의 배치에 이르기까지 중요합니다. 대칭과 비대칭 측면은 처음부터 정확해야 합니다. 단순함을 흥미롭게 보이게 하는 데는 어려움이 있으며, Beck은 이 점에서 자신을 밀어붙이는 것을 즐깁니다. 따라서 카르스텐 베크는 끊임없이 과거를 돌아보며 오래된 개념과 아이디어를 재작업하고 재정의합니다. 이런 식으로 그는 새로운 콘텐츠를 만들 수 있습니다. 가장 큰 차이점은 그가 콘크리트 아트에서 자신의 길을 찾았고 그것을 탐구하기 시작했다는 것입니다.',
};
const AndersSCRMNMeisner = {
    name: 'Anders SCRMN Meisner',
    info: 'Anders SCRMN Meisner는 주로 대규모 색채화, 세심한 펜 드로잉, 레이어 콜라주를 통해 소통합니다. SCRMN의 역사와 과학에 대한 평생의 관심은 그를 식민지주의, 종교의 풍경을 탐험하고, 예상치 못한 본능적인 어두운 미래로 여행하게 합니다. 이 여행은 앤틱 종이와 자연, 초상화, 해부학 그림을 사용하여 시작되었으며, 그는 이를 약간의 유머와 약간의 섭동으로 변경했습니다. 이러한 구체적인 역사 조각은 그에게 상징과 그 근거를 이해하는 방법을 나타내며, 역사적 형식으로 자신의 표현을 제시합니다. 자연은 항상 SCRMN의 작품에 존재합니다. 새(자연의 날아다니는 영웅), 꽃(아름다움으로 형성된 자연), 또는 인간의 상태와 감정을 보여주는 포유류(우리의 행동과 운명의 거울)가 그 예입니다. SCRMN은 Forårsudstillingen, Charlottenborg, Kunstnernes Efterårsudstilling, Den Frie Udstillingsbygning 및 Hans Alf Gallery와 함께 다양한 국제 미술 박람회에 전시했습니다.',
};
const EddieMartinez = {
    name: 'Eddie Martinez',
    info: '에디 마르티네즈의 열광적이고 대담하며 만화경적인 그림은 액션 페인팅 , 신 표현주의 , CoBrA 운동 과 같은 예술 역사적 전통에서 영감 을 얻었습니다. 마르티네즈는 거친 붓질, 다양한 매체, 추상적 형태와 리듬을 통해 미학적 선배들의 교리를 걸러냅니다. 그의 모티프는 종종 대중 문화에서 유래했으며 만화적인 오리, 두개골, 광대가 포함되었습니다. 마르티네즈는 뉴욕, 로스앤젤레스, 베를린, 런던, 스톡홀름, 서울 등 다른 도시에서 상업적으로 작품을 선보인 후, 디트로이트 현대 미술관 과 상하이 유즈 박물관 에서 개인전을 열면서 기관적 지원이 점차 커지고 있습니다 . 그의 작품은 카네기 미술관 , 국립 미술관 , 브롱크스 미술관 , 포트워스 현대 미술관 , 페레즈 미술관 , 국립 레이나 소피아 미술관, 롱 미술관, 유즈 박물관 등의 컬렉션에 속합니다. 마르티네즈의 캔버스 작품은 2차 시장에서 7자리 수의 가격에 판매되었습니다',
};
const DennisOsadebe = {
    name: 'Dennis Osadebe',
    info: '데니스 오사데베는 생생한 색조, 평평한 화면 평면, 팝 미학과 전통적인 나이지리아 공예에 대한 언급을 통해 현대 아프리카 생활을 묘사합니다. 나이지리아 태생의 라고스 거주 아티스트는 종종 캔버스를 디지털로 구성한 다음 대담한 아크릴 페인트와 보관용 안료 팔레트로 캔버스에 생명을 불어넣습니다. 독학으로 대학에서 경영학을 전공한 오사데베는 졸업 직후 전업 미술가로 전향했습니다. 그는 그 후 라고스, 케이프타운, 런던, 뉴욕, 로스앤젤레스에서 작품을 전시했습니다. 오사데베는 자신의 스타일을 "NEO"라고 부르는데, 이는 아프리카 예술에 대한 단순한 생각을 바로잡기 위해 만들어낸 "네오아프리카" 문화 운동을 지칭합니다. 오사데베는 밝고 긍정적이며 도발적인 이미지를 통해 서양의 제한적인 개념을 초월하는 진화하고 다면적인 아프리카 예술을 제시한다는 네오아프리카 이상을 구현하고자 합니다.',
};
const CharmingBaker = {
    name: 'Charming Baker',
    info: '영국의 예술가 Charming Baker는 전통적인 회화 기법과 현대적이고 종종 초현실적인 관점을 결합한 독특한 스타일로 유명합니다. 그의 작품은 삶의 역설을 탐구하고, 아름다움의 요소에 불안한 혼란을 불어넣는 것이 특징입니다. Baker는 종종 동물과 인물의 모티브를 사용하고, 자신의 작품을 조작하거나 손상시켜 예술의 신성함에 의문을 제기합니다. Baker의 작품은 상당한 국제적 찬사를 받았습니다. Central Saint Martins를 졸업한 그는 런던, 뉴욕, 로스앤젤레스를 포함한 여러 곳에서 개인전을 열며 전 세계적으로 전시했습니다. 그의 작품은 런던의 권위 있는 Victoria and Albert Museum에 소장되어 있습니다.',
};
const AyakoOkuda = {
    name: 'Ayako Okuda',
    info: '아야코 오쿠다는 전 세계를 여행하며, 자신이 찍은 사진 속 풍경과 사람들을 모티브로 그림을 제작합니다. 그녀의 그림의 특징으로, 작은(또는 큰) 사람들이 그녀의 그림에 묘사되어 있으며, 그것은 세상의 불확실성을 표현합니다. 또한, 그녀는 항상 화면에 눈부신 투명성을 가져다주는 밝은 빛을 표현하여 희망을 느끼게 하는 작품을 제작하려고 노력합니다.',
};
const FayeWeiWei = {
    name: 'Faye Wei Wei',
    info: '페이 웨이웨이의 초월적이고 시적인 그림은 상징적인 몽상과 신화적 도상학을 특징으로 합니다. 작가는 대형 캔버스에서 파스텔 색조와 차분한 흙빛을 결합하여 민속과 미술사에서 얻은 독특한 여성적 상징을 표현합니다. 그 결과는 몽환적이며 심리적 영역과 더 광범위한 사회적 문제를 탐구합니다. 웨이웨이는 성별과 사랑의 수행에 관심이 있습니다. 그녀는 슬레이드 미술 학교에서 학사 학위를 받았으며 런던, 뉴욕, 로스앤젤레스, 아테네, 비엔나, 상하이, 앤트워프 등 여러 도시에서 전시했습니다. 2019년 웨이웨이는 경매 회사 필립스와 협력하여 홍콩의 영국 문화원에서 의뢰를 받았습니다. 그녀의 작품은 런던의 컬렉션에 구매되었습니다.',
};
const JoachimBandau = {
    name: 'Joachim Bandau',
    info: '요아킴 반다우의 미니멀리스트 그림과 조각은 기하학적 형태의 교차점에 초점을 맞춘 단순하고 시적인 환상입니다. 그의 "검은 수채화" 시리즈(1983-)는 거의 움직이고 떨리는 것처럼 보이는 투명하고 겹쳐진 회색 직사각형의 수채화로 구성되어 있으며, 사진 필름, 패브릭, 그림자, 심지어 시간의 흐름을 암시합니다. 반다우는 "저는 작업 과정의 각 단계에 대해 완전한 자율성을 허용합니다."라고 말합니다. "모든 단계는 서로 상호 작용하지만 투명성은 가장 중요합니다. 레이어의 겹치는 과정이 계속되면서 새롭고 계획되지 않은 일이 나타나고 저와 제 작업 사이의 대화가 시작됩니다. 종종 작업 자체가 저를 안내합니다." 반다우의 3차원 작품도 기하학적이며, 단단한 모서리와 모서리가 있으며, 다면체 금속 마름모나 반짝이는 래커 상자 형태를 띱니다.',
};
const AndrewScott = {
    name: 'Andrew Scott',
};
const RonHicks = {
    name: 'Ron Hicks',
    info: '구상 화가 론 힉스의 인물과 실내는 너무 많은 디테일을 드러내거나 너무 적게 드러내는 것 사이의 균형을 이루려고 하며, 19세기 프랑스 인상주의 의 많은 예술적 고려 사항을 되살립니다 . 아마도 이러한 긴장에 대한 해독제로 힉스는 특정 공간과 모델의 형태와 빛을 강조합니다. 그는 "저는 형태를 중시합니다."라고 말합니다. "그 말은 제가 사물이나 사람보다는 형태로 사물을 더 많이 본다는 뜻입니다. 모든 것은 형태에 관한 것입니다. 중간 형태 대 큰 형태, 밝은 형태 대 어두운 형태." 그의 그림은 감정적이고 우울한 톤을 띠고 있으며, 그는 강렬한 붓놀림과 다양한 회색 음영을 사용하여 이를 달성합니다.',
};
const CaroleEisner = {
    name: 'Carole Eisner',
    info: '캐럴 아이스너는 공공 야외 공간에 자리 잡은 대규모의 기념비적인 조각품으로 가장 잘 알려져 있습니다. 공원, 박물관, 해안가 등에서 아이스너의 조각품은 주변 환경의 공간과 자연광에 참여하는데, 이는 종종 래커 처리된 금속에 반사됩니다. 아이스너는 녹슨 재활용 강철과 오래된 다리 조각품과 같은 발견된 물건에서 얻은 재료를 사용하여 재조립하고 새로운 형태로 용접합니다. 아이스너는 모든 소규모 또는 대규모 조각품에서 철, 강철 및 다양한 폐금속을 꼬아서 추상적이고 우아한 형태로 재구성하여 재료의 가단성을 탐구합니다. 이 모든 작업은 용접 토치를 사용합니다. 아이스너는 코네티컷주 웨스턴에 있는 자택에 딸린 스튜디오에서 작업하지만, 웨스턴과 뉴욕 시를 오가며 시간을 보내고 평생 뉴욕 사람이라고 자신을 정의합니다.',
};
const SusannahPhillips = {
    name: 'Susannah Phillips',
    info: '수잔나 필립스는 사실주의자 윌리엄 콜드스트림과 유안 우글로우 의 지도를 받았지만, 추상 표현주의 도 자신의 작업에 영향을 준 것으로 인용했습니다. 그녀는 구상과 추상을 혼합한 그림을 만듭니다. 필립스는 정물화, 실내, 초상화와 같이 회화의 역사에 친숙한 주제를 선택하지만, 넓은 붓놀림과 윤곽선의 이미지를 평평하게 하는 조합으로 이를 표현합니다. 필립스는 또한 제한된 색상 팔레트를 사용하여 빛과 색조의 차이를 불러일으키는 능력으로 유명합니다. 주로 회색과 중성색을 사용하며, 가끔 악센트 색상을 사용합니다. 그녀는 비슷한 생각을 가진 화가 그레이엄 닉슨, 로버트 벌린드 , 네오 라우흐 와 함께 작품을 전시했습니다 .',
};
const SamFrancis = {
    name: 'Sam Francis',
    info: '추상 표현주의 예술가 샘 프랜시스는 캔버스의 일부를 물감으로 튀기고 떨어뜨려, 덮이지 않은 빛나는 공허함을 강조했습니다.생동감 있는 색상 팔레트와 엄격한 흰색 패치 간의 이러한 대조는 공간, 색상 및 빛의 관계를 강조했습니다.프랜시스는 평생 동안 널리 여행하며 클로드 모네 의 "수련"에서 융 심리학과 일본 선불교의 미학에 이르기까지 다양한 영향에서 영감을 얻었습니다.그는 주요 기관에서 수십 개의 전시회를 가졌으며 1964년에는 제32회 베니스 비엔날레와 도큐멘타 3에 참여했습니다.오늘날 프랜시스는 퐁피두 센터 , 메트로폴리탄 미술관 , 바젤 미술관 등의 영구 컬렉션에 소장되어 있습니다.2차 시장에서 그의 작품은 종종 7자리 수의 가격을 차지합니다.',
};
const HyewonKim = {
    name: 'Hyewon Kim',
    gallery: gallery1,
};
const LeeSejun = {
    name: 'Lee Sejun',
    gallery: gallery1,
};
const ChangSungeun = {
    name: 'Chang Sungeun',
    information: 'Korean, b. 1978',
    gallery: gallery1,
};
const InKyungKwon = {
    name: 'In Kyung Kwon',
    information: 'South Korean, b. 1979',
    gallery: gallery2,
    info: '권인경 작가는 오래된 책 콜라주, 먹 케이크, 아크릴 물감 등 다양한 소재를 사용하여 이질적인 차원이 뒤섞인 모호하지만 강력한 도시 풍경을 만들어낸다. 파편화된 공간 이미지와 다른 시간대의 단절된 기억에서 태어난 이 초현실적인 풍경은 모든 사람 안에 숨겨진 상상력의 회로를 활성화시켜 의식의 경계를 넘어 흐르는 환상적인 콜라주를 경험하게 한다.',
    history: [
        '포스코미술관 신진작가 공모전(2016)',
        '한국작가프로젝트(한국사립미술관협회, 2016)',
        '서울시립미술관 신진작가 선정(2013)',
        '송은미술상 선정작가(2007)',
        '소장처: 국립현대미술관, 미술은행(2023, 2017, 2010, 2008), 양평군립미술관, 서울동부지검 신사옥 등',
    ],
};
const LeeKiyoung = {
    name: 'Lee Kiyoung',
    information: 'Korean, b. 1964',
    gallery: gallery2,
    info: '한국 전통 회화를 현대적 시각 언어로 재해석한 것으로 유명한 작가 이기영은 한국 종이에 시간, 행동, 생각을 겹쳐 놓는 과정을 중심으로 작업을 합니다. 이 작가는 종이에 먹물을 채우고 지우고 다시 채우는 반복적인 과정을 통해 시간과 생각의 흔적을 축적합니다. 작업의 마지막 단계는 날카로운 칼로 극도로 집중한 상태에서 복잡한 선을 새기고 이 선들을 안료로 채우는 것입니다. 처음에는 먹 케이크로 어두워진 한국 종이에 숨겨져 있던 이 깊고 강렬한 색의 선들이 미묘하게 드러나며 작품을 면밀히 살펴보게 합니다. 직사각형과 같은 기하학적 모양이 먹 케이크 배경을 초월하여 초월적이면서도 비어 있는 공간을 만들어냅니다. 인간의 삶에 대한 깊은 성찰에서 비롯된 이기영의 작품은 현대 미술에서 흔히 볼 수 없는 독특한 미학을 보여준다. 먹물과 음의 공간의 조화, 표면이 발산하는 평면성의 정점, 기하학적 선의 조합이 모두 어우러져 독특한 아름다움을 전달한다. 명상의 수행과 유사한 그들의 예술은 끝없는 지우기 행위를 통해 공허함의 미학을 제공한다.',
    history: [
        '이화여자대학교 한국화학과 교수',
        '소장품 : 국립현대미술관, 서울시립미술관, 이스라엘 한국대사관, 핀란드 한국대사관 등',
    ],
};
const JungJungyeob = {
    name: 'Jung Jungyeob',
    information: 'Korean, b. 1962',
    gallery: gallery2,
    info: '정정엽은 한국 페미니스트 미술 운동의 최전선에 있는 영향력 있는 예술가입니다. 그녀의 다양한 작품에는 그림, 설치 미술, 퍼포먼스가 포함되며, 페미니스트와 생태적 관점에 깊이 영향을 받았습니다. 그녀의 대표 컬렉션인 "팥 시리즈"는 여성의 보이지 않는 노동에 초점을 맞추고 작은 씨앗 하나하나에 담긴 지구의 활력을 포착한 것으로 호평을 받고 있습니다.정의 예술성은 캔버스를 넘어 더 광범위한 서사를 구현하는데, 이는 평범한 것(팥, 콩, 봄나물)에서 노동과 삶에 대한 논평을 끌어내는 것입니다. 그녀의 작업은 공존에 대한 지속적인 탐구이며, 일상적 존재의 실마리를 모든 생명체의 집단적 서사와 함께 엮어냅니다.',
    history: [
        '2022 이중섭미술상',
        '2020 성평등문화대상',
        '2019 고암 이응노미술상',
        '개인전 20여회 및 단체전 다수',
    ],
};
const ItsukiKaito = {
    name: 'Itsuki Kaito',
    information: 'Japanese, b. 1993',
    gallery: gallery2,
    info: '카이토 이츠키는 신화 속 초월적 영웅의 존재를 해체하고 그들의 자리를 수치심과 두려움으로 채웁니다. 여성에게 더 엄격한 예절이 요구되는 일본 사회에서 그녀는 부적절하고 부도덕하며 폭력적인 이미지를 통해 우리 몸 밖에서 우리에게 부과된 사회적 역할을 묘사합니다.',
    history: [
        '2024 Tang Contemporary Art, 베이징: 개인전',
        '2022 HIVE Center for Comtemporary Art, 베이징: 개인전',
        '2021 Tang Contemporary Art Hong Kong: 전시',
        '2022 HIVE Center for Contemporary Art, 베이징',
        '2021 Tang Contemporary Art, 홍콩',
    ],
};
const ChangukBak = {
    name: 'ChangukBak',
    information: 'Korean, b. 1982',
    gallery: gallery3,
    info: '박창욱은 한국의 떠오르는 추상화가입니다. 그는 자신의 추상적 표현과 스타일로 인간의 내면과 외면, 사람들의 존재의 문제, 관계 등을 찾아 독점적인 이미지와 패턴을 창조합니다.그의 독특한 작품은 고급 호텔과 다양한 박물관의 훌륭한 컬렉션에 포함되어 있습니다.',
};
const JungChoonpyo = {
    name: 'Jung Choonpyo',
    information: 'South Korean, b. 1966',
    gallery: gallery3,
    info: '정춘표는 한국에서 명성을 얻은 조각가입니다.그녀가 말했듯이 "제 작업은 제 인생에서 경험한 것을 포착하는 과정입니다." 그녀는 청동, 점토, 대리석을 사용하여 여성의 아름다움, 행운을 기원하는 북채, 사과, 작은 새, 사랑과 부의 상징과 같은 의미 있는 가치를 보여줍니다.',
};
const JEONGZIKSEONG = {
    name: 'JEONG ZIK SEONG',
    information: 'South Korean, b. 1976',
    gallery: gallery2,
    info: '정직성 작가는 끊임없이 회화의 영역을 확장하기 위해 실험을 거듭해 왔다. 그녀는 "반독립 주택", "공사장 추상", "블루 칼라/블루 컬러"와 같은 도시 풍경 시리즈에서 기하학적 추상 언어를 통해 현실적인 삶의 경험을 해석했다. 그녀는 또한 "현대적 나전 그림" 시리즈에서 나전의 물질성을 한국적 상징주의와 연결한다. 최근에는 바람과 비와 같은 대기의 변화에 ​​따라 숨쉬는 붓질과 함께 흐르는 다양한 심리적 형상의 층을 드러내는 작품을 선보이고 있다. 그녀의 이전 작업이 삶에서 추출한 기하학적 추상을 구현한 반면, 이제는 목적 없이 예기치 않게 그녀에게 다가오는 형상을 직관적으로 표현하는 보다 자유로운 과정으로 초점이 옮겨진다',
    history: [
        '2021년 공인당예술재단 올해의 작가상, 예술대상',
        '2012년 오늘의 작가상, 김종영 미술관',
        '소장처: 국립현대미술관, 서울시립미술관, 경기도미술관, 제주도립미술관, 서울대학교 미술관 등',
    ],
};
const JohannesDaniel = {
    name: 'Johannes Daniel',
    information: 'German, b. 1987',
    gallery: gallery5,
    info: '요하네스 다니엘은 라이프치히에 거주하는 독일 예술가로, 조각난 인간 형상을 묘사한 대규모 그래픽 페인팅을 제작합니다. 그는 유동적인 선과 파스텔 컬러를 통해 몽환적인 액체 세계를 그리며, 거친 그래피티와 도시적 미학과 대조를 이룹니다.',
};
const JungHyukPARK = {
    name: 'Jung Hyuk PARK',
    information: 'South Korean',
    gallery: gallery6,
};
const KIMIlChi = {
    name: 'KIM Il Chi',
    information: 'Korean',
    gallery: gallery6,
};
const HwiyeonKim = {
    name:'Hwiyeon Kim',
    information:'b. 1999',
    gallery:gallery7,

}
const artists = [
    AlanFears,
    CarstenBeck,
    AndersSCRMNMeisner,
    EddieMartinez,
    DennisOsadebe,
    CharmingBaker,
    AyakoOkuda,
    FayeWeiWei,
    JoachimBandau,
    AndrewScott,
    RonHicks,
    CaroleEisner,
    SusannahPhillips,
    SamFrancis,
    HyewonKim,
    LeeSejun,
    ChangSungeun,
    InKyungKwon,
    LeeKiyoung,
    JungJungyeob,
    ItsukiKaito,
    ChangukBak,
    JungChoonpyo,
    JEONGZIKSEONG,
    JohannesDaniel,
    JungHyukPARK,
    KIMIlChi,
    HwiyeonKim
];
const category = [
    'painting',
    'photography',
    '20th-Century Art',
    'Installation',
    'Sculpture',
];

const exhibition = [
    {
        name: JEONGZIKSEONG,
        gallery: gallery2,
        info: 'GalleryMEME에서 처음으로 선보이는 "물달관세음보살" 시리즈는 작가 특유의 강력한 붓놀림과 붉은 물감이 흘러내리는 열정적인 흔적을 통해 관능적이고 강렬한 세속적 종교화를 선보이며, 고려시대 불교화에 묘사된 기이한 암석 지형의 정토를 배경으로 하고 있다. 작가는 이를 "매우 평범하면서도 세속적인 삶에서 끌어낸 영성"이라고 설명한다',
        title: 'Layered Life',
        date: 'August 21 – September 22, 2024',
    },
    {
        name: JohannesDaniel,
        title: 'Platinum Tears',
        data: 'August 30 - September 30, 2024',
    },
    {
        name: JungHyukPARK,
        gallery: gallery6,
        title: 'BUBBLES PLUS +',
        info: '이번 버블플러스+ 전시는 2024년 새해맞이 기획전 "럭키버블쇼"에 참여했던 작가의 추천으로 진행되는 릴레이 특별전입니다.',
        date: 'August 28 – September 14, 2024',
    },
    {
        name:HwiyeonKim,
        gallery:gallery7,
        title:'FINGERPRINT',
        info:''
    }
];

const datas = [
    {
        id: 1,
        title: 'The Holiday Crush, 2019',
        price: 3800000,
        size: '29 9/10 x 40 1/5 x 4/5 인치 | 76 x 102 x 2cm',
        src: AlanFears1,
        frame: 'not included',
        materials: 'Acrylic on Canvas',
        rarity: 'Unique',
        release: 2019,
        category: 'painting',
        artist: AlanFears,
    },
    {
        id: 2,
        title: 'Uptown Down Town, 2020',
        price: 3500000,
        size: '17 7/10 × 23 3/5 × 4/5 in | 45 × 60 × 2 cm',
        src: AlanFears2,
        frame: 'not included',
        materials: 'Acrylic on Canvas',
        rarity: 'Unique',
        release: 2020,
        category: 'painting',
        artist: AlanFears,
    },
    {
        id: 3,
        title: 'The Entrepreneurs, 2021',
        price: 10200000,
        size: '40 1/5 × 50 × 4/5 in | 102 × 127 × 2 cm',
        src: AlanFears3,
        frame: 'not included',
        materials: 'Acrylic on Canvas',
        rarity: 'Unique',
        release: 2021,
        category: 'painting',
        artist: AlanFears,
    },
    {
        id: 4,
        title: 'The Gloves Are Coming Off, 2022',
        price: 6330000,
        size: '29 9/10 × 40 1/5 × 1 1/5 in | 76 × 102 × 3 cm',
        src: AlanFears4,
        frame: 'not included',
        materials: 'Acrylic on Canvas',
        rarity: 'Unique',
        release: 2022,
        category: 'painting',
        artist: AlanFears,
    },
    {
        id: 5,
        title: 'Alone Together, 2020',
        price: 3520000,
        size: '17 7/10 × 23 3/5 × 4/5 in | 45 × 60 × 2 cm',
        src: AlanFears5,
        frame: 'not included',
        materials: 'Acrylic on Canvas',
        rarity: 'Unique',
        release: 2020,
        category: 'painting',
        artist: AlanFears,
    },
    {
        id: 6,
        title: 'Konstruktion BC.01, 2023',
        price: 9320000,
        size: '43 3/10 × 51 1/5 × 1 3/5 in | 110 × 130 × 4 cm',
        src: CarstenBeck1,
        frame: 'included',
        materials: 'Oil on canvas',
        rarity: 'Unique',
        release: 2023,
        category: 'painting',
        artist: CarstenBeck,
    },
    {
        id: 7,
        title: 'Entre, 2022',
        price: 9330000,
        size: '43 3/10 × 51 1/5 × 1 3/5 in | 110 × 130 × 4 cm',
        src: CarstenBeck2,
        frame: 'included',
        materials: 'Oil on linen',
        rarity: 'Unique',
        release: 2022,
        category: 'painting',
        artist: CarstenBeck,
    },
    {
        id: 8,
        title: 'Liberté Toujours, 2024',
        price: 7400000,
        size: '41 3/10 × 35 2/5 in | 105 × 90 cm',
        src: AndersSCRMNMeisner1,
        frame: 'not included',
        materials: 'Acrylic on canvas',
        rarity: 'Unique',
        release: 2024,
        category: 'painting',
        artist: AndersSCRMNMeisner,
    },
    {
        id: 9,
        title: 'Freshwater Pearl Pose, 2022',
        price: 7400000,
        size: '59 1/10 × 74 4/5 in | 150 × 190 cm',
        src: AndersSCRMNMeisner2,
        frame: 'not included',
        materials: 'Oil on canvas',
        rarity: 'Unique',
        release: 2022,
        category: 'painting',
        artist: AndersSCRMNMeisner,
    },
    {
        id: 10,
        title: 'Bufly (GPBF), 2022',
        price: 7261000,
        size: '29 9/10 × 23 3/5 in | 76 × 60 cm',
        src: EddieMartinez1,
        frame: 'not included',
        materials: 'Screenprint on Arches BFK White 300gsm',
        rarity: 'Limited edition',
        release: 2022,
        category: 'painting',
        artist: EddieMartinez,
    },
    {
        id: 11,
        title: 'Two Untitled Drawings, Circa 2009',
        price: 3213000,
        size: '5 × 8 in | 12.7 × 20.3 cm',
        src: EddieMartinez2,
        frame: 'not included',
        materials: 'Felt tip pen on paper',
        rarity: 'Unique',
        release: 2009,
        category: 'painting',
        artist: EddieMartinez,
    },
    {
        id: 12,
        title: 'Connection, 2021',
        price: 3213000,
        size: '30 × 46 7/10 in | 76.2 × 118.6 cm',
        src: DennisOsadebe1,
        frame: 'not included',
        materials: 'Archival pigment ink, acrylic on canvas',
        rarity: 'Unique',
        release: 2021,
        category: 'painting',
        artist: DennisOsadebe,
    },
    {
        id: 13,
        title: 'Dream Sequence ( White Tee), 2019',
        price: 2213000,
        size: '24 × 24 in | 61 × 61 cm',
        src: DennisOsadebe2,
        frame: 'not included',
        materials: 'Giclee Somerset Velvet Fine Art Paper',
        rarity: 'Limited edition',
        release: 2019,
        category: 'painting',
        artist: DennisOsadebe,
    },
    {
        id: 14,
        title: 'Untitled, 2005',
        price: 2213000,
        size: '26 × 32 3/10 in | 66 × 82 cm',
        src: CharmingBaker1,
        frame: 'included',
        materials: 'Oil on canvas',
        rarity: 'Unique',
        release: 2005,
        category: 'painting',
        artist: CharmingBaker,
    },
    {
        id: 15,
        title: 'BEAUTIFUL PUSSY, 2023',
        price: 351000,
        size: '7 7/10 × 5 9/10 in | 19.5 × 15 cm',
        src: CharmingBaker2,
        frame: 'included',
        materials: 'Archival Inkjet on Somerset Satin 330gsm Paper',
        rarity: 'Limited edition',
        release: 2023,
        category: 'painting',
        artist: CharmingBaker,
    },
    {
        id: 16,
        title: 'Untiled, 2022',
        price: 1740000,
        size: '23 9/10 × 28 3/5 in | 60.6 × 72.7 cm',
        src: AyakoOkuda1,
        frame: 'included',
        materials: 'Oil on canvas',
        rarity: 'Unique',
        release: 2022,
        category: 'painting',
        artist: AyakoOkuda,
    },
    {
        id: 17,
        title: 'Untitled, 2021',
        price: 1340000,
        size: '20 9/10 × 20 9/10 in | 53 × 53 cm',
        src: AyakoOkuda2,
        frame: 'included',
        materials: 'Oil on canvas',
        rarity: 'Unique',
        release: 2021,
        category: 'painting',
        artist: AyakoOkuda,
    },
    {
        id: 18,
        title: 'Robbie, 2024',
        price: 1480000,
        size: '9 4/5 × 7 3/10 in | 25 × 18.5 cm',
        src: FayeWeiWei1,
        frame: 'included',
        materials: 'Oil and watercolour on paper',
        rarity: 'Unique',
        release: 2024,
        category: 'painting',
        artist: FayeWeiWei,
    },
    {
        id: 19,
        title: 'An Echo Trapped Forever, 2022',
        price: 2533900,
        size: '22 × 15 in | 56 × 38 cm',
        src: FayeWeiWei2,
        frame: 'Not included',
        materials: 'Oil and watercolour on paper',
        rarity: 'Unique',
        release: 2022,
        category: 'painting',
        artist: FayeWeiWei,
    },
    {
        id: 20,
        title: 'Push (Printers Proof Edition), 2023',
        price: 5092000,
        size: '17 1/2 × 13 in | 44.5 × 33 cm',
        src: AndrewScott1,
        frame: 'included',
        materials:
            'Watercolor Paper, Altered Frame & Hand Drawn Digital Illustration',
        rarity: 'Limited edition',
        release: 2023,
        category: 'painting',
        artist: AndrewScott,
    },
    {
        id: 21,
        title: 'The Boxer, 2023',
        price: 2369800,
        size: '17 1/2 × 13 in | 44.5 × 33 cm',
        src: AndrewScott2,
        frame: 'included',
        materials:
            'Watercolor paper with broken glass and hand drawn digital illustration',
        rarity: 'Limited edition',
        release: 2023,
        category: 'painting',
        artist: AndrewScott,
    },
    {
        id: 22,
        title: 'The Boxer, 2023',
        price: 2369800,
        size: '17 1/2 × 13 in | 44.5 × 33 cm',
        src: AndrewScott2,
        frame: 'included',
        materials:
            'Watercolor paper with broken glass and hand drawn digital illustration',
        rarity: 'Limited edition',
        release: 2023,
        category: 'painting',
        artist: AndrewScott,
    },
    {
        id: 23,
        title: 'Pull, 2024',
        price: 3978000,
        size: '17 1/2 × 13 in | 44.5 × 33 cm',
        src: AndrewScott3,
        frame: 'Not included',
        materials:
            'Hand varnished Giclée on Matt Cotton Archival canvas hand finished with string',
        rarity: 'Limited edition',
        release: 2023,
        category: 'painting',
        artist: AndrewScott,
    },
    {
        id: 24,
        title: 'Pause, 2024',
        price: 12600000,
        size: '20 × 16 in | 50.8 × 40.6 cm',
        src: RonHicks1,
        frame: 'Not included',
        materials: 'Oil on cradled panel',
        rarity: 'Unique',
        release: 2024,
        category: 'painting',
        artist: RonHicks,
    },
    {
        id: 25,
        title: 'Axiomatic Appeal, 2020',
        price: 12600000,
        size: '12 × 12 in | 30.5 × 30.5 cm',
        src: RonHicks2,
        frame: 'included',
        materials: 'Oil on Board',
        rarity: 'Unique',
        release: 2020,
        category: 'painting',
        artist: RonHicks,
    },
    {
        id: 26,
        title: 'Voyage, 1987',
        price: 17900000,
        size: '50 × 73 in | 127 × 185.4 cm',
        src: CaroleEisner1,
        frame: 'Not included',
        materials: 'Acrylic on canvas',
        rarity: 'Unique',
        release: 1987,
        category: '20th-Century Art',
        artist: CaroleEisner,
    },
    {
        id: 27,
        title: 'Quattro, 1987',
        price: 18790000,
        size: '70 × 57 in | 177.8 × 144.8 cm',
        src: CaroleEisner2,
        frame: 'Not included',
        materials: 'Acrylic on canvas',
        rarity: 'Unique',
        release: 1987,
        category: '20th-Century Art',
        artist: CaroleEisner,
    },
    {
        id: 28,
        title: 'Untitled, 1999',
        price: 6678000,
        size: '12 × 16 in | 30.5 × 40.6 cm',
        src: SusannahPhillips1,
        frame: 'included',
        materials: 'Oil on linen',
        rarity: 'Unique',
        release: 1999,
        category: '20th-Century Art',
        artist: SusannahPhillips,
    },
    {
        id: 29,
        title: 'Untitled, 2016',
        price: 5342000,
        size: '10 × 12 in | 25.4 × 30.5 cm',
        src: SusannahPhillips2,
        frame: 'included',
        materials: 'Oil on canvas',
        rarity: 'Unique',
        release: 2016,
        category: '20th-Century Art',
        artist: SusannahPhillips,
    },
    {
        id: 30,
        title: 'Untitled, 2016',
        price: 5342000,
        size: '16 × 10 in | 40.6 × 25.4 cm',
        src: SusannahPhillips3,
        frame: 'included',
        materials: 'Oil on canvas',
        rarity: 'Unique',
        release: 2016,
        category: '20th-Century Art',
        artist: SusannahPhillips,
    },
    {
        id: 31,
        title: 'Untitled, 1994',
        price: 6010000,
        size: '21 × 18 in | 53.4 × 45.7 cm',
        src: SamFrancis1,
        frame: 'Not included',
        materials: 'Etching',
        rarity: 'Unique',
        release: 1994,
        category: '20th-Century Art',
        artist: SamFrancis,
    },
    {
        id: 32,
        title: 'Untitled (SF82-263), 1982',
        price: 125000000,
        size: '14 × 19 1/10 in | 35.5 × 48.5 cm',
        src: SamFrancis2,
        frame: 'Not included',
        materials: 'Acrylic on paper',
        rarity: 'Unique',
        release: 1982,
        category: '20th-Century Art',
        artist: SamFrancis,
    },
    {
        id: 33,
        title: 'SF78-210 , 1978',
        price: 38747000,
        size: '9 4/5 × 15 7/10 in | 25 × 40 cm',
        src: SamFrancis3,
        frame: 'Not included',
        materials: 'Acrylic on paper',
        rarity: 'Unique',
        release: 1978,
        category: '20th-Century Art',
        artist: SamFrancis,
    },
    {
        id: 34,
        title: 'Interior of a mysterious bus, 2023',
        price: 4800000,
        size: '57 3/10 × 38 1/5 in | 145.5 × 97 cm',
        src: HyewonKim1,
        frame: 'Not included',
        materials: 'Watercolor, gouache, acrylic medium on canvas',
        rarity: 'Unique',
        release: 2023,
        category: 'painting',
        artist: HyewonKim,
    },
    {
        id: 35,
        title: 'Public phones and vending machines on the platform of Sindorim station line 2, 2022',
        price: 7200000,
        size: '57 3/10 × 38 1/5 in | 145.5 × 97 cm',
        src: HyewonKim2,
        frame: 'Not included',
        materials: 'Watercolor, gouache, acrylic medium on canvas',
        rarity: 'Unique',
        release: 2022,
        category: 'painting',
        artist: HyewonKim,
    },
    {
        id: 36,
        title: '공유하는 꿈, 2024',
        price: 1200000,
        size: '12 1/2 × 12 1/2 in | 31.7 × 31.7 cm',
        src: LeeSejun1,
        frame: 'Not included',
        materials: 'Acrylic on linen',
        rarity: 'Unique',
        release: 2024,
        category: 'painting',
        artist: LeeSejun,
    },
    {
        id: 37,
        title: 'Geological painting _노을인 동시에 산이면서 바람인 그림, 2024',
        price: 1200000,
        size: '12 1/2 × 12 1/2 in | 31.7 × 31.7 cm',
        src: LeeSejun2,
        frame: 'Not included',
        materials: 'Acrylic, fluorescent pigment, mixed media on Linen',
        rarity: 'Unique',
        release: 2024,
        category: 'painting',
        artist: LeeSejun,
    },
    {
        id: 38,
        title: '지층적 회화 _빛나는 물결, 2024',
        price: 1200000,
        size: '17 9/10 × 20 9/10 in | 45.5 × 53 cm',
        src: LeeSejun3,
        frame: 'Not included',
        materials: 'Acrylic, fluorescent pigment on Linen',
        rarity: 'Unique',
        release: 2024,
        category: 'painting',
        artist: LeeSejun,
    },
    {
        id: 39,
        title: 'Gentle fluctuation, 2022',
        price: 1700000,
        size: '29 1/2 × 39 2/5 in | 75 × 100 cm',
        src: ChangSungeun1,
        frame: 'Not included',
        materials: 'Archival pigment print',
        rarity: 'Limited edition',
        release: 2022,
        category: 'photography',
        artist: ChangSungeun,
    },
    {
        id: 40,
        title: '불가능한 풍경9, 2019',
        price: 2100000,
        size: '10 1/2 × 15 7/10 in | 26.6 × 40 cm',
        src: ChangSungeun2,
        frame: 'Not included',
        materials: 'Archival pigment print',
        rarity: 'Limited edition',
        release: 2019,
        category: 'photography',
        artist: ChangSungeun,
    },
    {
        id: 41,
        title: '불가능한 풍경5, 2019',
        price: 2100000,
        size: '18 9/10 × 12 3/5 in | 48 × 32 cm',
        src: ChangSungeun3,
        frame: 'Not included',
        materials: 'Archival pigment print',
        rarity: 'Limited edition',
        release: 2019,
        category: 'photography',
        artist: ChangSungeun,
    },
    {
        id: 42,
        title: 'A Private room-An added memory 개인의 방 - 덧댄 기억, 2022',
        price: 20040000,
        size: '76 × 51 3/5 in | 193 × 131 cm',
        src: InKyungKwon1,
        frame: 'Not included',
        materials: 'Mixed media on Korean paper (Acrylic, Collage, Ink cake)',
        rarity: 'Unique',
        release: 2022,
        category: 'painting',
        artist: InKyungKwon,
    },
    {
        id: 43,
        title: 'Different memories 1 서로 다른 기억들 1, 2023',
        price: 20040000,
        size: '76 2/5 × 51 1/5 in | 194 × 130 cm',
        src: InKyungKwon2,
        frame: 'included',
        materials: 'Mixed media on Korean paper (Acrylic, Collage, Ink cake)',
        rarity: 'Unique',
        release: 2023,
        category: 'painting',
        artist: InKyungKwon,
    },
    {
        id: 44,
        title: 'A different memory, 2023',
        price: 5345000,
        size: '27 3/10 × 26 in | 69.3 × 66 cm',
        src: InKyungKwon3,
        frame: 'included',
        materials: 'Chinese ink and Acrylic on korean paper',
        rarity: 'Unique',
        release: 2023,
        category: 'painting',
        artist: InKyungKwon,
    },
    {
        id: 45,
        title: 'Subsequent answer 3123, 2023',
        price: 53452000,
        size: '65 × 47 1/5 in | 165 × 120 cm',
        src: LeeKiyoung1,
        frame: 'included',
        materials: 'Ink cake pigment mixed media on Korean paper',
        rarity: 'Unique',
        release: 2023,
        category: 'painting',
        artist: LeeKiyoung,
    },
    {
        id: 46,
        title: 'Sprout 5 싹 5, 2015',
        price: 40089000,
        size: '63 4/5 × 51 1/5 in | 162 × 130 cm',
        src: JungJungyeob1,
        frame: 'Not included',
        materials: 'Acrylic and oil on canvas',
        rarity: 'Unique',
        release: 2015,
        category: 'painting',
        artist: JungJungyeob,
    },
    {
        id: 47,
        title: 'Sprout 3 싹 3, 2015',
        price: 40089000,
        size: '63 4/5 × 51 1/5 in | 162 × 130 cm',
        src: JungJungyeob2,
        frame: 'Not included',
        materials: 'Acrylic and oil on canvas',
        rarity: 'Unique',
        release: 2015,
        category: 'painting',
        artist: JungJungyeob,
    },
    {
        id: 48,
        title: 'Sprout 7 싹 7, 2015',
        price: 40089000,
        size: '55 1/10 × 102 2/5 in | 140 × 260 cm',
        src: JungJungyeob3,
        frame: 'Not included',
        materials: 'Acrylic and oil on canvas',
        rarity: 'Unique',
        release: 2015,
        category: 'painting',
        artist: JungJungyeob,
    },
    {
        id: 49,
        title: 'Tools are validated (Nurturing a chick), 2023',
        price: 8016000,
        size: '20 9/10 × 17 9/10 in | 53 × 45.5 cm',
        src: ItsukiKaito1,
        frame: 'included',
        materials: 'Oil on canvas',
        rarity: 'Unique',
        release: 2023,
        category: 'painting',
        artist: ItsukiKaito,
    },
    {
        id: 50,
        title: 'Feeding birds (Under the light), 2023',
        price: 6680000,
        size: '20 9/10 × 13 1/10 in | 53 × 33.3 cm',
        src: ItsukiKaito2,
        frame: 'included',
        materials: 'Oil and charcoal on canvas',
        rarity: 'Unique',
        release: 2023,
        category: 'painting',
        artist: ItsukiKaito,
    },
    {
        id: 51,
        title: 'Feeding birds (Pink machine), 2023',
        price: 8016000,
        size: '20 9/10 × 17 9/10 in | 53 × 45.5 cm',
        src: ItsukiKaito3,
        frame: 'included',
        materials: 'Oil and charcoal on canvas',
        rarity: 'Unique',
        release: 2023,
        category: 'painting',
        artist: ItsukiKaito,
    },
    {
        id: 52,
        title: 'The path of contact #5, 2014',
        price: 17271000,
        size: '63 9/10 × 51 3/10 in | 162.2 × 130.3 cm',
        src: ChangukBak1,
        frame: 'Not included',
        materials: 'Charcoal, marble powder, acrylic on canvas',
        rarity: 'Unique',
        release: 2014,
        category: 'painting',
        artist: ChangukBak,
        description:
            '물리적 접근과 기억 시간에 대한 행동은 상관관계가 있는 것으로 간주됩니다. 접촉 지점에 접근할수록 더 명확해지고 접촉 지점에서 멀어질수록 더 흐릿해집니다.우리의 기억은 번쩍이고 접촉의 순간을 떠올립니다. 우리는 기억을 계속하기 위해 접촉 지점을 달성하려고 노력합니다.',
    },
    {
        id: 53,
        title: 'The path of contact #7, 2014',
        price: 17271000,
        size: '63 9/10 × 51 3/10 in | 162.2 × 130.3 cm',
        src: ChangukBak2,
        frame: 'Not included',
        materials: 'Charcoal, marble powder, acrylic on canvas',
        rarity: 'Unique',
        release: 2014,
        category: 'painting',
        artist: ChangukBak,
        description:
            '그들은 연결되어 있다. 믿음의 움직임은 서로를 중심으로 돈다. 내가 움직여도 상대방이 움직이지 않으면 내 믿음은 사라진다. 둘의 관계는 존재와 같다. 셋의 관계는 넷의 존재다.',
    },
    {
        id: 54,
        title: 'The path of contact #8, 2014',
        price: 29899000,
        size: '102 × 76 2/5 in | 259 × 194 cm',
        src: ChangukBak3,
        frame: 'Not included',
        materials: 'Charcoal, marble powder, acrylic on canvas',
        rarity: 'Unique',
        release: 2014,
        category: 'painting',
        artist: ChangukBak,
        description:
            '한 가지 움직임이 아이디어를 대변하는 것은 아니다. 모든 움직임의 합이 아이디어가 아니다. 움직일 가능성에 대한 선택의 합이 내적 궤적이다.',
    },
    {
        id: 55,
        title: 'like water, like wind, 2020',
        price: 19880000,
        size: '51 1/5 × 98 2/5 in | 130 × 250 cm',
        src: JungChoonpyo1,
        frame: 'included',
        materials: 'Aluminium on canvas',
        rarity: 'Unique',
        release: 2020,
        category: 'Sculpture',
        artist: JungChoonpyo,
    },
    {
        id: 56,
        title: 'like water, like wind2, 2020',
        price: 19880000,
        size: '39 2/5 × 78 7/10 in | 100 × 200 cm',
        src: JungChoonpyo2,
        frame: 'included',
        materials: 'Aluminium on canvas',
        rarity: 'Unique',
        release: 2020,
        category: 'Sculpture',
        artist: JungChoonpyo,
    },
    {
        id: 57,
        title: 'Beautiful dream, 2021',
        price: 32000000,
        size: '1299 1/5 × 2385 4/5 in | 3300 × 6060 cm',
        src: JungChoonpyo3,
        frame: 'Not included',
        materials: 'Synthetic resins, painted urethane',
        rarity: 'Unique',
        release: 2021,
        category: 'Installation',
        artist: JungChoonpyo,
    },
    {
        id: 58,
        title: '수월관음보살도 Water-moon Avalakiteshvara 202426, 2024',
        price: 43851000,
        size: '76 3/10 × 51 3/10 in | 193.9 × 130.3 cm',
        src: ZikSeongJeong1,
        frame: 'Not included',
        materials: 'Acrylic and oil on canvas',
        rarity: 'Unique',
        release: 2024,
        category: 'Painting',
        artist: JEONGZIKSEONG,
    },
    {
        id: 59,
        title: '수월관음보살도 Water-moon Avalakiteshvara 202427, 2024',
        price: 43851000,
        size: '76 3/10 × 51 3/10 in | 193.9 × 130.3 cm',
        src: ZikSeongJeong2,
        frame: 'Not included',
        materials: 'Acrylic and oil on canvas',
        rarity: 'Unique',
        release: 2024,
        category: 'Painting',
        artist: JEONGZIKSEONG,
    },
    {
        id: 60,
        title: '수월관음보살도 Water-moon Avalakiteshvara 202428, 2024',
        price: 43851000,
        size: '76 3/10 × 51 3/10 in | 193.9 × 130.3 cm',
        src: ZikSeongJeong3,
        frame: 'Not included',
        materials: 'Acrylic and oil on canvas',
        rarity: 'Unique',
        release: 2024,
        category: 'Painting',
        artist: JEONGZIKSEONG,
    },
    {
        id: 61,
        title: 'Still Life 202347, 2023',
        price: 21261000,
        size: '46 × 35 4/5 in | 116.8 × 91 cm',
        src: ZikSeongJeong4,
        frame: 'Not included',
        materials: 'Acrylic and oil on canvas',
        rarity: 'Unique',
        release: 2023,
        category: 'Painting',
        artist: JEONGZIKSEONG,
    },
    {
        id: 62,
        title: '201710 Green Pool, 2017',
        price: 13288000,
        size: '24 1/5 × 27 1/5 in | 61.5 × 69 cm',
        src: ZikSeongJeong5,
        frame: 'included',
        materials: 'Acrylic and oil on canvas, frame',
        rarity: 'Unique',
        release: 2017,
        category: 'Painting',
        artist: JEONGZIKSEONG,
    },
    {
        id: 63,
        title: 'Sing me to sleep (humdrum town), 2024',
        price: 6692200,
        size: '29 1/2 × 23 3/5 in | 75 × 60 cm',
        src: JohannesDaniel1,
        frame: 'Not included',
        materials: 'Oil on canvas',
        rarity: 'Unique',
        release: 2024,
        category: 'Painting',
        artist: JohannesDaniel,
    },
    {
        id: 64,
        title: 'These are the days, 2024',
        price: 18887000,
        size: '86 3/5 × 63 in | 220 × 160 cm',
        src: JohannesDaniel2,
        frame: 'Not included',
        materials: 'Oil on canvas',
        rarity: 'Unique',
        release: 2024,
        category: 'Painting',
        artist: JohannesDaniel,
    },
    {
        id: 65,
        title: 'My body moves (It goes without me), 2024',
        price: 18887000,
        size: '19 7/10 × 15 7/10 in | 50 × 40 cm',
        src: JohannesDaniel3,
        frame: 'Not included',
        materials: 'Oil on canvas',
        rarity: 'Unique',
        release: 2024,
        category: 'Painting',
        artist: JohannesDaniel,
    },
    {
        id: 66,
        title: 'End of season (so honest and so perfect), 2023',
        price: 6692000,
        size: '29 1/2 × 23 3/5 in | 75 × 60 cm',
        src: JohannesDaniel4,
        frame: 'Not included',
        materials: 'Oil on canvas',
        rarity: 'Unique',
        release: 2023,
        category: 'Painting',
        artist: JohannesDaniel,
    },
    {
        id: 67,
        title: 'These are the days, 2024',
        price: 18886000,
        size: '86 3/5 × 63 in | 220 × 160 cm',
        src: JohannesDaniel5,
        frame: 'Not included',
        materials: 'Oil on canvas',
        rarity: 'Unique',
        release: 2024,
        category: 'Painting',
        artist: JohannesDaniel,
    },
    {
        id: 68,
        title: 'Park_s land 39, 2024',
        price: 5377700,
        size: '23 3/5 in diameter | 60 cm diameter',
        src: JungHyukPARK1,
        frame: 'Not included',
        materials: 'Oil on canvas',
        rarity: 'Unique',
        release: 2024,
        category: 'Painting',
        artist: JungHyukPARK,
    },
    {
        id: 69,
        title: 'Park_s land 40, 2024',
        price: 5377700,
        size: '23 3/5 in diameter | 60 cm diameter',
        src: JungHyukPARK2,
        frame: 'Not included',
        materials: 'Oil on canvas',
        rarity: 'Unique',
        release: 2024,
        category: 'Painting',
        artist: JungHyukPARK,
    },
    {
        id: 70,
        title: 'Eerolling, 2023',
        price: 1075000,
        size: '15 7/10 in diameter | 40 cm diameter',
        src: KIMIlChi1,
        frame: 'Not included',
        materials: 'Acrylic on canvas',
        rarity: 'Unique',
        release: 2023,
        category: 'Painting',
        artist: KIMIlChi,
    },
    {
        id: 71,
        title: 'Evolling, 2024',
        price: 2016000,
        size: '23 3/5 in diameter | 60 cm diameter',
        src: KIMIlChi2,
        frame: 'Not included',
        materials: 'Acrylic on canvas',
        rarity: 'Unique',
        release: 2024,
        category: 'Painting',
        artist: KIMIlChi,
    },
    {
        id: 72,
        title: 'Face-to-Face 1, 2024',
        price: 510900,
        size: '13 1/10 × 9 1/2 in | 33.4 × 24.2 cm',
        src: HwiyeonKim1,
        frame: 'Not included',
        materials: 'Acrylic on canvas',
        rarity: 'Unique',
        release: 2024,
        category: 'Painting',
        artist: HwiyeonKim,
    },
    {
        id: 73,
        title: 'Layers of Trace 2, 2024',
        price: 605000,
        size: '16 1/10 × 12 1/2 in | 40.9 × 31.8 cm',
        src: HwiyeonKim2,
        frame: 'Not included',
        materials: 'Acrylic on canvas',
        rarity: 'Unique',
        release: 2024,
        category: 'Painting',
        artist: HwiyeonKim,
    },
    {
        id: 74,
        title: 'Layers of Trace 3, 2024',
        price: 510900,
        size: '16 1/10 × 12 1/2 in | 40.9 × 31.8 cm',
        src: HwiyeonKim3,
        frame: 'Not included',
        materials: 'Acrylic on canvas',
        rarity: 'Unique',
        release: 2024,
        category: 'Painting',
        artist: HwiyeonKim,
    },
];

export { artists, datas, category, exhibition, slide };
